[versions]
kotlin = "2.2.10"
cradle = "5.7.1-dev"
logback = "1.5.29"

[libraries]
th2-bom = { group = "com.exactpro.th2", name = "bom", version = "4.14.3" }
th2-common = { group = "com.exactpro.th2", name = "common", version = "5.17.2-dev" }
th2-cradle-cassandra = { group = "com.exactpro.th2", name = "cradle-cassandra", version.ref = "cradle" }
th2-grpc-service-generator = { group = "com.exactpro.th2", name = "grpc-service-generator", version = "3.8.5" }
th2-grpc-check1 = { group = "com.exactpro.th2", name = "grpc-check1", version = "4.5.2" }

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.14" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.28.0" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

junit-bom = { group = "org.junit", name = "junit-bom", version = "5.14.2" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version = "2.0.3" }

[plugins]
th2-publish = { id = "com.exactpro.th2.gradle.publish", version = "0.3.14" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }
compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }